### ISSUE TITLE
RENAME! Angular4 is ahead!

### ISSUE THREAD

**Issue by amcdnl** [AngularClass/awesome-angular#183]
LOLZ, but seriously we need to rename to be 2+... How about `awesome-ngx` ?

**Comment by rolandjitsu** [comment]
That is true. @gdi2290 what do you think?

**Comment by gdi2290** [comment]
yeah true this now conflicts with someone else's awesome-angular which covers angular1

**Comment by rolandjitsu** [comment]
I saw that, and I think there's more than one `awesome-angular` out there. Maybe @amcdnl's suggestion could work? Although, having the same repo name is technically permitted by git as it is under a different user, and the framework itself uses simply angular for most of the npm packages (the scope) and the main repo is also just angular.

**Comment by gdi2290** [comment]
true, it should be totally fine to call it the same name and just mention the difference in the readme

**Comment by rolandjitsu** [comment]
Do you want to do it? Or should I?

**Comment by gdi2290** [comment]
let's hold off until angular 4 stable is released

**Comment by rolandjitsu** [comment]
👍

**Comment by rolandjitsu** [comment]
The name of the repo is now renamed, closing this.
