### ISSUE TITLE
AngularClass github page not working

### ISSUE THREAD

**Issue by kichnan** [AngularClass/awesome-angular#217]
As of right now, the [AngularClass github page](https://angularclass.github.io/awesome-angular2/) is not working. https://angularclass.github.io/awesome-angular2/
It says "There isn't a GitHub Pages site here." Just thought I'd inform.

![image](https://cloud.githubusercontent.com/assets/1217487/24283082/9ab44f5c-1089-11e7-9432-3d6ce0939fd6.png)

**Comment by rolandjitsu** [comment]
@kichnan I think the url is at [awesome-angular](https://angularclass.github.io/awesome-angular) now.
