### ISSUE TITLE
Possible new reactive component example

### ISSUE THREAD

**Issue by dinony** [AngularClass/awesome-angular#229]
Hi!

Not an issue, but a proposal. I've published an angular component, which handles virtual scrolling, where I tried to use observables for the most parts of the component surface and inner implementation. I've also provided  examples, which touch upon the topics:

- Advanced rxjs usage (~20 operators, subscription, scheduling, hot/cold observables, creating custom observables, ...)
- Using reactive forms
- Using Angular material
- Basic Angular library layout and design
- AoT compilation
- Tools: systemjs / rollup / gulp
- Module formats: umd / fesm5 / fesm15

The [lib](https://github.com/dinony/od-virtualscroll) and demos are up to date (Angular 4.1.0).

If you think it could be useful for people learning Angular, I'm happy to add it to this list. 

Yours,
dinony

**Comment by rolandjitsu** [comment]
Feel free to make a PR and add your lib to the list 👍
